apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: mpi-example
  namespace: default
spec:
  runPolicy:
    cleanPodPolicy: Running
  slotsPerWorker: 2
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  mpirun --allow-run-as-root -np 2 /opt/allreduce;
              image: openbce/mpi-example:v0.1
              name: launcher
    Worker:
      replicas: 1
      template:
        spec:
          containers:
            - image: openbce/mpi-example:v0.1
              name: worker
              resources:
                limits:
                  cpu: 2

